version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: algolabyrinth_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: algolabyrinth_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/algolabyrinth
    restart: on-failure

volumes:
  mongodb_data:
